### ISSUE TITLE
Milestones [10/16/2016]

### ISSUE THREAD

**Issue by jbae11** [jbae11/2016-bae-borehole-ihlrwm#12]
### milestones
- [x] be explicit about the metric
- [x]  statement saying the metric is homemade
- [x] main tex for them all
- [x] figure out bibliography
- [x] abstract: motivation / results/ my contributions
- [x] ntroduction: rest to understand the paper
- [x] methodology: how to reproduce my results - equations and all
- [x]  results and discussion: everything learned
- [x] citation: where i got the data (the data was scraped from public information)
- [x] explain why the weights are they way they are.
- [x]  skilled worker existence 
- [x] cost of treatment licenses.

**Comment by katyhuff** [comment]
This has been handled and can be closed. When a commit is pushed to the repository that fixes some or all of an issue, it is helpful to go to the issue and bring it up to date. If that is too much effort, then the interaction can also be handled in the commit message by referencing the issue number ( in this case #12).
